version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: realestate-postgres
    environment:
      - POSTGRES_DB=realestate
      - POSTGRES_USER=realestate
      - POSTGRES_PASSWORD=realestate_pass
      - TZ=Asia/Tokyo
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "5432:5432"
    networks:
      - realestate-network

  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    container_name: realestate-backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app/backend
      - ./data:/app/data
      - ./logs:/app/logs
      - /etc/localtime:/etc/localtime:ro
    environment:
      - PYTHONUNBUFFERED=1
      - DATABASE_URL=postgresql://realestate:realestate_pass@postgres:5432/realestate
      - TZ=Asia/Tokyo
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=admin_password
      # 開発時の認証バイパス（本番環境では必ずfalseにすること）
      - DISABLE_ADMIN_AUTH=true
      # スクレイパー設定（デフォルト値）
      - SCRAPER_DETAIL_REFETCH_DAYS=90  # 詳細ページ再取得間隔（日）。0に設定すると常に再取得
      # 常に詳細を再取得したい場合は下記のコメントを解除
      # - SCRAPER_DETAIL_REFETCH_DAYS=0  # 全スクレイパーで常に詳細を再取得
      # スクレイパー個別設定の例（必要に応じてコメントアウトを解除）
      # - SCRAPER_SUUMO_DETAIL_REFETCH_DAYS=60
      # - SCRAPER_HOMES_DETAIL_REFETCH_DAYS=30
      # 再販物件の再活性化期間（デフォルト60日）
      - REACTIVATION_THRESHOLD_DAYS=60  # 販売終了から指定日数以内なら既存データを再活性化、超過したら新規登録
      # メール送信設定（本番環境用）
      # - MAIL_USERNAME=your-email@gmail.com
      # - MAIL_PASSWORD=your-app-password
      # - MAIL_SERVER=smtp.gmail.com
      # - MAIL_PORT=587
      # - MAIL_FROM=noreply@yourdomain.com
      # - MAIL_FROM_NAME=都心マンションDB
      # - MAIL_STARTTLS=True
      # - MAIL_SSL_TLS=False
      - FRONTEND_URL=${FRONTEND_URL}
      # Google OAuth設定（開発環境用）
      # .envファイルから読み込み
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_CLIENT_SECRET=${GOOGLE_CLIENT_SECRET}
      - GOOGLE_REDIRECT_URI=${GOOGLE_REDIRECT_URI}
      # Cookie設定（開発環境用）
      - COOKIE_SECURE=true
      - COOKIE_SAMESITE=lax
    command: poetry run uvicorn backend.app.main:app --host 0.0.0.0 --port 8000
    depends_on:
      - postgres
    networks:
      - realestate-network

  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    container_name: realestate-frontend
    ports:
      - "3001:3001"
    volumes:
      - ./frontend:/app
      - ./certs:/app/certs:ro
      - /app/node_modules
      - /etc/localtime:/etc/localtime:ro
    environment:
      # VITE_API_URL を削除してプロキシを使用
      - TZ=Asia/Tokyo
    command: npm run dev -- --host 0.0.0.0 --port 3001
    depends_on:
      - backend
    networks:
      - realestate-network

  # scraperサービスは無効化（管理画面からのみスクレイピングを実行）
  # scraper:
  #   build:
  #     context: .
  #     dockerfile: docker/backend/Dockerfile
  #   container_name: realestate-scraper
  #   volumes:
  #     - ./backend:/app/backend
  #     - ./data:/app/data
  #     - ./logs:/app/logs
  #     - /etc/localtime:/etc/localtime:ro
  #   environment:
  #     - PYTHONUNBUFFERED=1
  #     - DATABASE_URL=postgresql://realestate:realestate_pass@postgres:5432/realestate
  #     - TZ=Asia/Tokyo
  #   command: poetry run python backend/scripts/run_scrapers.py --schedule --interval 6
  #   depends_on:
  #     - postgres
  #     - backend
  #   networks:
  #     - realestate-network

networks:
  realestate-network:
    driver: bridge

volumes:
  postgres_data: